serve:
  public:
    port: 4444

  admin:
    port: 4445

urls:
  self:
    issuer: http://localhost:4444

  login: http://localhost:3000/login
  consent: http://localhost:3000/consent
  logout: http://localhost:3000/logout

log:
  level: debug
  format: text

oauth2:
  expose_internal_errors: true