package ee.bytecore.backend.graphql.mappers;

import com.netflix.dgs.codegen.generated.types.CreateUserInput;
import com.netflix.dgs.codegen.generated.types.PaymentMethodType;
import com.netflix.dgs.codegen.generated.types.Role;
import ee.bytecore.backend.entities.user.User;
import ee.bytecore.backend.entities.user.UserAddress;
import ee.bytecore.backend.entities.user.UserPaymentMethod;

import java.util.List;

public class UserMapper {

    // Mapping ee.bytecore.backend.enums.UserRole into generated by netflix dgs Role
    public static com.netflix.dgs.codegen.generated.types.User toGraphQlType(User entity) {
        if (entity == null) {
            return null;
        }
        return com.netflix.dgs.codegen.generated.types.User.newBuilder()
                .id(entity.getId().toString())
                .username(entity.getUsername())
                .email(entity.getEmail())
                .role(mapRole(entity.getRole()))
                .dateOfBirth(entity.getDateOfBirth())
                .createdAt(entity.getCreatedAt())
                .updatedAt(entity.getUpdatedAt())
                .addresses(List.of())
                .paymentMethods(List.of())
                .build();
    }

    public static com.netflix.dgs.codegen.generated.types.UserAddress toGraphQlType(UserAddress entity) {
        if (entity == null) {
            return null;
        }
        return com.netflix.dgs.codegen.generated.types.UserAddress.newBuilder()
                .id(entity.getId().toString())
                .firstName(entity.getFirstName())
                .lastName(entity.getLastName())
                .city(entity.getCity())
                .country(entity.getCountry())
                .postalCode(entity.getPostalCode())
                .addressLine1(entity.getAddressLine1())
                .addressLine2(entity.getAddressLine2())
                .mobile(entity.getMobile())
                .createdAt(entity.getCreatedAt())
                .updatedAt(entity.getUpdatedAt())
                .build();
    }

    public static com.netflix.dgs.codegen.generated.types.UserPaymentMethod toGraphQlType(UserPaymentMethod entity) {
        if (entity == null) {
            return null;
        }

        return com.netflix.dgs.codegen.generated.types.UserPaymentMethod.newBuilder()
                .id(entity.getId().toString())
                .provider(entity.getProvider())
                .type(mapPaymentMethodType(entity.getType()))
                .createdAt(entity.getCreatedAt())
                .updatedAt(entity.getUpdatedAt())
                .build();
    }

    // Mapping ee.bytecore.backend.enums.UserRole into generated by netflix dgs Role
    private static Role mapRole (ee.bytecore.backend.enums.UserRole role) {
        return role == null ? null : Role.valueOf(role.name());
    }

    private static PaymentMethodType mapPaymentMethodType (ee.bytecore.backend.enums.PaymentMethodType type) {
        return  type == null ? null : PaymentMethodType.valueOf(type.name());
    }
}

//TODO change return null to custom exception
