import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { codegen } from "@graphql-codegen/core";
import * as operations from "@graphql-codegen/typescript-operations";
import { buildSchema, parse, print, validate } from "graphql";

const schemaSource = await readFile(new URL("../../infrastructure/hive/supergraph.graphql", import.meta.url), "utf8");
const document = parse(await readFile(new URL("../src/lib/graphql/operations.graphql", import.meta.url), "utf8"));
const schema = buildSchema(schemaSource);
const errors = validate(schema, document);
if (errors.length) throw new Error(errors.map((error) => error.message).join("\n"));
const generated = await codegen({
  filename: "generated.ts",
  schema,
  documents: [{ document }],
  plugins: [{ operations: {} }],
  pluginMap: { operations },
  config: {
    onlyOperationTypes: true,
    enumsAsTypes: true,
    skipTypename: true,
    useTypeImports: true,
    strictScalars: true,
    scalars: {
      BigDecimal: "Decimal",
      UUID: "UUID",
      JSON: "JsonValue",
      Instant: "string", LocalDate: "string", Url: "string",
      link__Import: "unknown", join__FieldSet: "string",
    },
  },
});
const queries = document.definitions.map((definition) => {
  if (definition.kind !== "OperationDefinition" || !definition.name) throw new Error("Named operations required");
  return `export const ${definition.name.value}Source = ${JSON.stringify(print({ kind: "Document", definitions: [definition] }))};`;
}).join("\n");
const content = `// Generated by bun run graphql:generate; do not edit.\n// Composed schema SHA-256: ${createHash("sha256").update(schemaSource).digest("hex")}\nimport type { Decimal, JsonValue, UUID } from "./scalars";\n${generated}\n${queries}\n`;
const output = new URL("../src/lib/graphql/generated.ts", import.meta.url);
if (process.argv.includes("--check")) {
  if (await readFile(output, "utf8") !== content) throw new Error("GraphQL output is stale; run bun run graphql:generate");
} else {
  await writeFile(output, content);
}
console.log("Composed schema operations validated; generated output " + (process.argv.includes("--check") ? "matches." : "updated."));
