// Generated by bun run graphql:generate; do not edit.
// Composed schema SHA-256: 822a81726b5f9b234ab604cd0c136b9e0ef1b399928184025a7aecc0e4629763
import type { Decimal, JsonValue, UUID } from "./scalars";
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type CheckoutShippingMethod =
  | 'EXPRESS'
  | 'PICKUP'
  | 'STANDARD';

export type OrderStatus =
  | 'CANCELLED'
  | 'COMPLETED'
  | 'PAID'
  | 'PENDING'
  | 'SHIPPING';

export type ProductSort =
  | 'PRICE_ASC'
  | 'PRICE_DESC'
  | 'RATING_DESC'
  | 'RELEVANCE';

export type ProductAttributeFilterInput = {
  name: string;
  value: string;
};

export type ProductFilterInput = {
  attributes?: Array<ProductAttributeFilterInput> | null | undefined;
  categoryId?: string | number | null | undefined;
  inStock?: boolean | null | undefined;
  maxPrice?: Decimal | null | undefined;
  minPrice?: Decimal | null | undefined;
};

/**
 * Catalog discovery (search/filters/sort/suggestions). PostgreSQL-backed MVP:
 *
 * - Search matches Product.name, Product.description, and ProductVariant.sku
 *   (ILIKE + pg_trgm indexes) — no external search engine.
 * - categoryId filters by DIRECT category membership only; parent/child
 *   category hierarchy is not expanded to descendants in this MVP.
 * - minPrice/maxPrice/attributes/inStock are variant-level filters and must
 *   all be satisfied by the SAME ProductVariant to match a product.
 * - Sorting: RELEVANCE (simple deterministic name/description/sku ranking,
 *   only meaningful with a non-blank query), PRICE_ASC/PRICE_DESC (using the
 *   minimum price among a product's filter-matching variants), RATING_DESC
 *   (persisted average, highest first, unrated last). All ties use product ID ascending.
 * - Facets are computed over the population that already matches the search
 *   query and filters (no per-facet self-exclusion).
 */
export type ProductSearchInput = {
  filters?: ProductFilterInput | null | undefined;
  page?: number | null | undefined;
  query?: string | null | undefined;
  size?: number | null | undefined;
  sort?: ProductSort | null | undefined;
};

export type IntegrationShippingOptionsQueryVariables = Exact<{
  countryCode?: string | null | undefined;
}>;


export type IntegrationShippingOptionsQuery = { checkoutShippingOptions: Array<{ method: CheckoutShippingMethod, charge: Decimal, currency: string, estimate: string, supportedCountries: Array<string> }> };

export type IntegrationGuestCartQueryVariables = Exact<{ [key: string]: never; }>;


export type IntegrationGuestCartQuery = { guestCart: { id: string, expiresAt: string, totals: { subtotal: Decimal, currency: string }, items: Array<{ id: string, quantity: number, subtotal: Decimal, productVariant: { id: string, sku: string, price: Decimal, attributes: JsonValue, isActive: boolean } }> } | null };

export type IntegrationGuestOrderQueryVariables = Exact<{
  publicId?: UUID | null | undefined;
  requestId?: UUID | null | undefined;
}>;


export type IntegrationGuestOrderQuery = { guestOrder: { publicId: UUID, requestId: UUID, status: OrderStatus, totals: { merchandiseSubtotal: Decimal, shippingCharge: Decimal, total: Decimal, currency: string } } | null };

export type CatalogCategoriesQueryVariables = Exact<{ [key: string]: never; }>;


export type CatalogCategoriesQuery = { categories: Array<{ id: string, name: string, slug: string, parent: { id: string } | null }> };

export type CatalogListingQueryVariables = Exact<{
  input: ProductSearchInput;
}>;


export type CatalogListingQuery = { searchProducts: { items: Array<{ id: string, name: string, slug: string, averageRating: number | null, ratingCount: number, variants: Array<{ id: string, price: Decimal, isActive: boolean }> }>, pageInfo: { page: number, size: number, totalItems: number, totalPages: number }, facets: { categories: Array<{ id: string, name: string, count: number }>, attributes: Array<{ name: string, values: Array<{ value: string, count: number }> }>, price: { min: Decimal | null, max: Decimal | null } } } };

export type CatalogSuggestionsQueryVariables = Exact<{
  query: string;
  limit?: number | null | undefined;
}>;


export type CatalogSuggestionsQuery = { productSearchSuggestions: Array<{ productId: string, name: string, slug: string }> };

export type HomeDiscoveryQueryVariables = Exact<{ [key: string]: never; }>;


export type HomeDiscoveryQuery = { searchProducts: { facets: { categories: Array<{ id: string, name: string, count: number }> } } };

export type HomeCategoryProductsQueryVariables = Exact<{
  categoryId: string | number;
}>;


export type HomeCategoryProductsQuery = { searchProducts: { items: Array<{ id: string, name: string, slug: string, averageRating: number | null, ratingCount: number, variants: Array<{ id: string, price: Decimal, isActive: boolean }> }>, pageInfo: { page: number, size: number, totalItems: number, totalPages: number } } };

export type ProductDetailQueryVariables = Exact<{
  slug: string;
}>;


export type ProductDetailQuery = { product: { id: string, name: string, slug: string, description: string | null, averageRating: number | null, ratingCount: number, categories: Array<{ id: string, name: string, slug: string }>, variants: Array<{ id: string, sku: string, price: Decimal, attributes: JsonValue, isActive: boolean, barcode: string | null, weightGrams: number | null }> } | null };

export const IntegrationShippingOptionsSource = "query IntegrationShippingOptions($countryCode: String) {\n  checkoutShippingOptions(countryCode: $countryCode) {\n    method\n    charge\n    currency\n    estimate\n    supportedCountries\n  }\n}";
export const IntegrationGuestCartSource = "query IntegrationGuestCart {\n  guestCart {\n    id\n    expiresAt\n    totals {\n      subtotal\n      currency\n    }\n    items {\n      id\n      quantity\n      subtotal\n      productVariant {\n        id\n        sku\n        price\n        attributes\n        isActive\n      }\n    }\n  }\n}";
export const IntegrationGuestOrderSource = "query IntegrationGuestOrder($publicId: UUID, $requestId: UUID) {\n  guestOrder(publicId: $publicId, requestId: $requestId) {\n    publicId\n    requestId\n    status\n    totals {\n      merchandiseSubtotal\n      shippingCharge\n      total\n      currency\n    }\n  }\n}";
export const CatalogCategoriesSource = "query CatalogCategories {\n  categories {\n    id\n    name\n    slug\n    parent {\n      id\n    }\n  }\n}";
export const CatalogListingSource = "query CatalogListing($input: ProductSearchInput!) {\n  searchProducts(input: $input) {\n    items {\n      id\n      name\n      slug\n      averageRating\n      ratingCount\n      variants {\n        id\n        price\n        isActive\n      }\n    }\n    pageInfo {\n      page\n      size\n      totalItems\n      totalPages\n    }\n    facets {\n      categories {\n        id\n        name\n        count\n      }\n      attributes {\n        name\n        values {\n          value\n          count\n        }\n      }\n      price {\n        min\n        max\n      }\n    }\n  }\n}";
export const CatalogSuggestionsSource = "query CatalogSuggestions($query: String!, $limit: Int) {\n  productSearchSuggestions(query: $query, limit: $limit) {\n    productId\n    name\n    slug\n  }\n}";
export const HomeDiscoverySource = "query HomeDiscovery {\n  searchProducts(input: {page: 0, size: 1, sort: PRICE_ASC}) {\n    facets {\n      categories {\n        id\n        name\n        count\n      }\n    }\n  }\n}";
export const HomeCategoryProductsSource = "query HomeCategoryProducts($categoryId: ID!) {\n  searchProducts(\n    input: {page: 0, size: 4, sort: PRICE_ASC, filters: {categoryId: $categoryId}}\n  ) {\n    items {\n      id\n      name\n      slug\n      averageRating\n      ratingCount\n      variants {\n        id\n        price\n        isActive\n      }\n    }\n    pageInfo {\n      page\n      size\n      totalItems\n      totalPages\n    }\n  }\n}";
export const ProductDetailSource = "query ProductDetail($slug: String!) {\n  product(slug: $slug) {\n    id\n    name\n    slug\n    description\n    categories {\n      id\n      name\n      slug\n    }\n    averageRating\n    ratingCount\n    variants {\n      id\n      sku\n      price\n      attributes\n      isActive\n      barcode\n      weightGrams\n    }\n  }\n}";
