// Generated by bun run graphql:generate; do not edit.
// Composed schema SHA-256: c3bff035ccb23304dfa63a8c9078ea33b4d8ac3d1c4fc137a121bdfa489259aa
import type { Decimal, JsonValue, UUID } from "./scalars";
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type CheckoutShippingMethod =
  | 'EXPRESS'
  | 'PICKUP'
  | 'STANDARD';

export type OrderStatus =
  | 'CANCELLED'
  | 'COMPLETED'
  | 'PAID'
  | 'PENDING'
  | 'SHIPPING';

export type IntegrationShippingOptionsQueryVariables = Exact<{
  countryCode?: string | null | undefined;
}>;


export type IntegrationShippingOptionsQuery = { checkoutShippingOptions: Array<{ method: CheckoutShippingMethod, charge: Decimal, currency: string, estimate: string, supportedCountries: Array<string> }> };

export type IntegrationGuestCartQueryVariables = Exact<{ [key: string]: never; }>;


export type IntegrationGuestCartQuery = { guestCart: { id: string, expiresAt: string, totals: { subtotal: Decimal, currency: string }, items: Array<{ id: string, quantity: number, subtotal: Decimal, productVariant: { id: string, sku: string, price: Decimal, attributes: JsonValue, isActive: boolean } }> } | null };

export type IntegrationGuestOrderQueryVariables = Exact<{
  publicId?: UUID | null | undefined;
  requestId?: UUID | null | undefined;
}>;


export type IntegrationGuestOrderQuery = { guestOrder: { publicId: UUID, requestId: UUID, status: OrderStatus, totals: { merchandiseSubtotal: Decimal, shippingCharge: Decimal, total: Decimal, currency: string } } | null };

export const IntegrationShippingOptionsSource = "query IntegrationShippingOptions($countryCode: String) {\n  checkoutShippingOptions(countryCode: $countryCode) {\n    method\n    charge\n    currency\n    estimate\n    supportedCountries\n  }\n}";
export const IntegrationGuestCartSource = "query IntegrationGuestCart {\n  guestCart {\n    id\n    expiresAt\n    totals {\n      subtotal\n      currency\n    }\n    items {\n      id\n      quantity\n      subtotal\n      productVariant {\n        id\n        sku\n        price\n        attributes\n        isActive\n      }\n    }\n  }\n}";
export const IntegrationGuestOrderSource = "query IntegrationGuestOrder($publicId: UUID, $requestId: UUID) {\n  guestOrder(publicId: $publicId, requestId: $requestId) {\n    publicId\n    requestId\n    status\n    totals {\n      merchandiseSubtotal\n      shippingCharge\n      total\n      currency\n    }\n  }\n}";
