input AddCartItemInput {
  productVariantId: ID!
  quantity: Int!
}

input UpdateCartItemInput {
  quantity: Int!
}

extend type Mutation {
  addCartItem(input: AddCartItemInput!): CartItem!
  updateCartItem(cartItemId: ID!, input: UpdateCartItemInput!): CartItem!
  removeCartItem(cartItemId: ID!): Boolean!
  clearCart: Boolean!
  startGuestCart: StartGuestCartResult!
  addGuestCartItem(input: AddCartItemInput!): GuestCart!
  updateGuestCartItem(cartItemId: ID!, input: UpdateCartItemInput!): GuestCart!
  removeGuestCartItem(cartItemId: ID!): GuestCart!
  mergeGuestCart(requestId: UUID!): GuestCartMergeResult!
}
