spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/retail"
    username: retail
    password: retail

dgs:
  graphql:
    graphiql:
      enabled: true
    introspection:
      enabled: true
