spring:
  profiles:
    default: dev
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: validate
  docker:
    compose:
      file: ../infrastructure/compose.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:4444

logging:
  level:
    com.zaxxer.hikari: WARN
    org.hibernate: WARN
    org.springframework.orm.jpa: WARN
    org.springframework.boot.autoconfigure.orm.jpa: WARN
