spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  graphql:
    graphiql:
      enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

kratos:
  admin-url: ${KRATOS_ADMIN_URL}

dgs:
  graphql:
    introspection:
      enabled: false
    graphiql:
      enabled: false