spring:
  profiles:
    default: dev
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.zaxxer.hikari: WARN
    org.hibernate: WARN
    org.springframework.orm.jpa: WARN
    org.springframework.boot.autoconfigure.orm.jpa: WARN
